# -*- coding: utf-8 -*-
"""네이버지식인_증상_크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yfXN_KATndvFF353GqLbOsRb2tYEEOB9
"""

import requests
import json
import pandas as pd

# 네이버 API 키
naver_api_key = 'YOUR_NAVER_API_KEY'

# 검색어 설정
query = '위염 증상'

# 검색 결과를 저장할 리스트
questions = []
answers = []

# 검색할 페이지 수 (1페이지당 10개의 결과)
num_pages = 10

for page in range(1, num_pages + 1):
    # 네이버 지식인 API URL
    url = f'https://openapi.naver.com/v1/search/kin.json?query={query}&display=100&start={((page - 1) * 100) + 1}'

    # API 요청 헤더 설정
    headers = {
        'X-Naver-Client-Id': 'or2cQJHgkB6II3HrE8wR',
        'X-Naver-Client-Secret': 'pPEKQVVFku'
    }

    # API 요청
    response = requests.get(url, headers=headers)
    data = response.json()

    # 검색 결과에서 질문과 답변 추출
    for item in data['items']:
        questions.append(item['title'])
        answers.append(item['description'])

# 추출된 데이터를 데이터프레임으로 변환
df = pd.DataFrame({'Question': questions, 'Answer': answers})

# 데이터프레임을 CSV 파일로 저장
df.to_csv('naver_kin_stomach.csv', index=False)

print(f'Total {len(questions)} questions and answers crawled.')

pd.read_csv('naver_kin_cold.csv')

import requests
import json
import pandas as pd

# 네이버 API 키
naver_api_key = 'YOUR_NAVER_API_KEY'

# 검색어 설정
query = '위염 초기 증상'

# 검색 결과를 저장할 리스트
questions = []
answers = []

# 검색할 페이지 수 (1페이지당 10개의 결과)
num_pages = 10

for page in range(1, num_pages + 1):
    # 네이버 지식인 API URL
    url = f'https://openapi.naver.com/v1/search/kin.json?query={query}&display=100&start={((page - 1) * 100) + 1}'

    # API 요청 헤더 설정
    headers = {
        'X-Naver-Client-Id': 'or2cQJHgkB6II3HrE8wR',
        'X-Naver-Client-Secret': 'pPEKQVVFku'
    }

    # API 요청
    response = requests.get(url, headers=headers)
    data = response.json()

    # 검색 결과에서 질문과 답변 추출
    for item in data['items']:
        questions.append(item['title'])
        answers.append(item['description'])

# 추출된 데이터를 데이터프레임으로 변환
df = pd.DataFrame({'Question': questions, 'Answer': answers})

# 데이터프레임을 CSV 파일로 저장
df.to_csv('naver_kin_stomach_2.csv', index=False)

print(f'Total {len(questions)} questions and answers crawled.')

pd.read_csv('naver_kin_cold_2.csv')

import requests
import json
import pandas as pd

# 네이버 API 키
naver_api_key = 'YOUR_NAVER_API_KEY'

# 검색어 설정
query = '위염'

# 검색 결과를 저장할 리스트
questions = []
answers = []

# 검색할 페이지 수 (1페이지당 10개의 결과)
num_pages = 10

for page in range(1, num_pages + 1):
    # 네이버 지식인 API URL
    url = f'https://openapi.naver.com/v1/search/kin.json?query={query}&display=100&start={((page - 1) * 100) + 1}'

    # API 요청 헤더 설정
    headers = {
        'X-Naver-Client-Id': 'or2cQJHgkB6II3HrE8wR',
        'X-Naver-Client-Secret': 'pPEKQVVFku'
    }

    # API 요청
    response = requests.get(url, headers=headers)
    data = response.json()

    # 검색 결과에서 질문과 답변 추출
    for item in data['items']:
        questions.append(item['title'])
        answers.append(item['description'])

# 추출된 데이터를 데이터프레임으로 변환
df = pd.DataFrame({'Question': questions, 'Answer': answers})

# 데이터프레임을 CSV 파일로 저장
df.to_csv('naver_kin_stomach_3.csv', index=False)

print(f'Total {len(questions)} questions and answers crawled.')

pd.read_csv('naver_kin_cold_3.csv')

import requests
import json
import pandas as pd

# 네이버 API 키
naver_api_key = 'YOUR_NAVER_API_KEY'

# 검색어 설정
query = '위염 빨리 낫는법'

# 검색 결과를 저장할 리스트
questions = []
answers = []

# 검색할 페이지 수 (1페이지당 10개의 결과)
num_pages = 10

for page in range(1, num_pages + 1):
    # 네이버 지식인 API URL
    url = f'https://openapi.naver.com/v1/search/kin.json?query={query}&display=100&start={((page - 1) * 100) + 1}'

    # API 요청 헤더 설정
    headers = {
        'X-Naver-Client-Id': 'or2cQJHgkB6II3HrE8wR',
        'X-Naver-Client-Secret': 'pPEKQVVFku'
    }

    # API 요청
    response = requests.get(url, headers=headers)
    data = response.json()

    # 검색 결과에서 질문과 답변 추출
    for item in data['items']:
        questions.append(item['title'])
        answers.append(item['description'])

# 추출된 데이터를 데이터프레임으로 변환
df = pd.DataFrame({'Question': questions, 'Answer': answers})

# 데이터프레임을 CSV 파일로 저장
df.to_csv('naver_kin_stomach_4.csv', index=False)

print(f'Total {len(questions)} questions and answers crawled.')

"""###csv 파일 병합"""

# glob is a library to find pathnames using regex patterns
import os
import glob
import pandas as pd

os.chdir("/content/stomach")
extension = 'csv' #csv로 파일 확장자 지정
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ]) #지정한 파일 경로에 있는 모든 파일 불러오기
#export to csv
combined_csv.to_csv( "combined_stomach.csv", index=False, encoding='utf-8-sig')
#combined_csv는 병합할 파일명으로 각자 변경하면 된다.
#인코딩을 반드시! 해줘야 한다. 안그러면 깨진다.

pd.read_csv('combined_stomach.csv')

pd.read_csv('/content/eyes/combined_eyes.csv')

pd.read_csv('/content/cold/combined_cold.csv')